title: lahavpadan.github.io
description: Notes on machine learning, cyber, cryptography, physics, and electrical engineering.
url: "https://lahavpadan.github.io"
baseurl: ""
profile_image: "/assets/images/whoami/me.png"

markdown: kramdown
kramdown:
  input: Kramdown
  math_engine: mathjax
  syntax_highlighter: rouge

exclude:
  - templates